/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.1.10.0                                              */
/*  Date (dd.mm.yyyy): 15. 4.2022   Time (hh:mm): 17:22                        */
/*******************************************************************************/


#ifndef _BMTEST_DISPLAY_1_RESOURCES_H_
#define _BMTEST_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_24XRGB
#define DISPLAY_1_X_RESOLUTION 900
#define DISPLAY_1_Y_RESOLUTION 600
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define DISPLAY_1_COLOR_TABLE_SIZE 29

/* Font ID definitions                                                         */

#define DISPLAY_1_FONT_TABLE_SIZE 4

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_VECTOR__10_ 5
#define GX_PIXELMAP_ID_VECTOR__11_ 6
#define GX_PIXELMAP_ID_VECTOR__12_ 7
#define GX_PIXELMAP_ID_VECTOR__13_ 8
#define GX_PIXELMAP_ID_VECTOR__14_ 9
#define GX_PIXELMAP_ID_VECTOR__15_ 10
#define GX_PIXELMAP_ID_VECTOR__16_ 11
#define GX_PIXELMAP_ID_VECTOR__9_ 12
#define GX_PIXELMAP_ID__4_ 13
#define GX_PIXELMAP_ID___15_PM 14
#define DISPLAY_1_PIXELMAP_TABLE_SIZE 15

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_1 1
#define GX_STRING_ID_STRING_2 2
#define GX_STRING_ID_STRING_3 3
#define GX_STRING_ID_STRING_4 4
#define GX_STRING_ID_STRING_5 5
#define GX_STRING_ID_STRING_6 6
#define GX_STRING_ID_STRING_7 7
#define GX_STRING_ID_STRING_8 8
#define GX_STRING_ID_STRING_9 9
#define GX_STRING_ID_STRING_10 10
#define GX_STRING_ID_STRING_11 11
#define GX_STRING_ID_STRING_12 12
#define GX_STRING_ID_STRING_13 13
#define GX_STRING_ID_STRING_14 14
#define GX_STRING_ID_STRING_15 15
#define GX_STRING_ID_STRING_16 16
#define GX_STRING_ID_STRING_17 17
#define GX_STRING_ID_STRING_18 18
#define GX_STRING_ID_STRING_19 19
#define GX_STRING_ID_STRING_20 20
#define GX_STRING_ID_STRING_21 21
#define DISPLAY_1_STRING_TABLE_SIZE 22

#endif                                       /* sentry                         */
